package com.alfahdtv.app;

import android.app.Activity;import android.app.DownloadManager;import android.content.Intent;import android.database.Cursor;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.view.Gravity;import android.view.View;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import java.util.Locale;

public final class DownloadsActivity extends Activity {
    private LinearLayout list;
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(AppUi.BG);build();load();}
    private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(AppUi.BG);root.setPadding(AppUi.dp(this,16),AppUi.dp(this,14),AppUi.dp(this,16),0);TextView head=AppUi.text(this,"‹   التنزيلات",24,Color.WHITE);head.setTypeface(null,1);head.setOnClickListener(v->finish());root.addView(head,new LinearLayout.LayoutParams(-1,AppUi.dp(this,56)));ScrollView scroll=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private void load(){list.removeAllViews();DownloadManager dm=(DownloadManager)getSystemService(DOWNLOAD_SERVICE);try(Cursor c=dm.query(new DownloadManager.Query())){int count=0;while(c.moveToNext()&&count<100){long id=c.getLong(c.getColumnIndexOrThrow(DownloadManager.COLUMN_ID));String title=c.getString(c.getColumnIndexOrThrow(DownloadManager.COLUMN_TITLE));int status=c.getInt(c.getColumnIndexOrThrow(DownloadManager.COLUMN_STATUS));long done=c.getLong(c.getColumnIndexOrThrow(DownloadManager.COLUMN_BYTES_DOWNLOADED_SO_FAR)),total=c.getLong(c.getColumnIndexOrThrow(DownloadManager.COLUMN_TOTAL_SIZE_BYTES));String state=status==DownloadManager.STATUS_SUCCESSFUL?"اكتمل":status==DownloadManager.STATUS_RUNNING?"جاري التحميل":status==DownloadManager.STATUS_FAILED?"فشل":"في الانتظار";String percent=total>0?" • "+(done*100/total)+"%":"";LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(AppUi.dp(this,16),AppUi.dp(this,14),AppUi.dp(this,16),AppUi.dp(this,14));card.setBackground(AppUi.round(AppUi.PANEL,15,this));TextView name=AppUi.text(this,title==null?"ملف فيديو":title,16,Color.WHITE);name.setTypeface(null,1);card.addView(name);TextView meta=AppUi.text(this,state+percent,13,status==DownloadManager.STATUS_FAILED?AppUi.RED:AppUi.MUTED);meta.setPadding(0,AppUi.dp(this,7),0,0);card.addView(meta);if(status==DownloadManager.STATUS_SUCCESSFUL)card.setOnClickListener(v->{Uri uri=dm.getUriForDownloadedFile(id);if(uri!=null){Intent i=new Intent(Intent.ACTION_VIEW).setDataAndType(uri,"video/*").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivity(i);}catch(Exception ignored){}}});LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.bottomMargin=AppUi.dp(this,10);list.addView(card,cp);count++;}if(count==0){TextView empty=AppUi.text(this,"لا توجد تنزيلات حتى الآن",17,AppUi.MUTED);empty.setGravity(Gravity.CENTER);list.addView(empty,new LinearLayout.LayoutParams(-1,AppUi.dp(this,300)));}}}
    @Override protected void onResume(){super.onResume();if(list!=null)load();}
}
