package com.alfahdtv.app;

import android.app.Activity;import android.content.Intent;import android.content.SharedPreferences;import android.graphics.Color;import android.os.Bundle;import android.view.Gravity;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import java.util.ArrayList;import java.util.Collections;import java.util.Set;

public final class LibraryActivity extends Activity {
    private LinearLayout list;private SharedPreferences data;
    @Override protected void onCreate(Bundle b){super.onCreate(b);data=getSharedPreferences("data",0);getWindow().setStatusBarColor(AppUi.BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(AppUi.dp(this,16),AppUi.dp(this,14),AppUi.dp(this,16),0);root.setBackgroundColor(AppUi.BG);TextView head=AppUi.text(this,"‹   مكتبتي",24,Color.WHITE);head.setTypeface(null,1);head.setOnClickListener(v->finish());root.addView(head,new LinearLayout.LayoutParams(-1,AppUi.dp(this,55)));LinearLayout tabs=new LinearLayout(this);TextView fav=AppUi.action(this,"المفضلة");TextView history=AppUi.action(this,"شوهد مؤخرًا");tabs.addView(fav,new LinearLayout.LayoutParams(0,AppUi.dp(this,48),1));LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(0,AppUi.dp(this,48),1);hp.setMarginStart(AppUi.dp(this,8));tabs.addView(history,hp);root.addView(tabs);ScrollView scroll=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));fav.setOnClickListener(v->show("favorites"));history.setOnClickListener(v->show("history"));setContentView(root);show("favorites");}
    private void show(String key){list.removeAllViews();Set<String> raw=data.getStringSet(key,Collections.emptySet());ArrayList<String> items=new ArrayList<>(raw);Collections.reverse(items);for(String item:items){int pos=item.lastIndexOf('|');if(pos<0)continue;String title=item.substring(0,pos),url=item.substring(pos+1);TextView row=AppUi.text(this,"▶   "+title,15,Color.WHITE);row.setMaxLines(2);row.setPadding(AppUi.dp(this,15),AppUi.dp(this,10),AppUi.dp(this,15),AppUi.dp(this,10));row.setBackground(AppUi.round(AppUi.PANEL,14,this));row.setOnClickListener(v->{startActivity(new Intent(this,MainActivity.class).putExtra("open_url",url).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));finish();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,AppUi.dp(this,64));p.topMargin=AppUi.dp(this,10);list.addView(row,p);}if(items.isEmpty()){TextView empty=AppUi.text(this,key.equals("favorites")?"المفضلة فارغة حاليًا":"لا يوجد سجل مشاهدة",16,AppUi.MUTED);empty.setGravity(Gravity.CENTER);list.addView(empty,new LinearLayout.LayoutParams(-1,AppUi.dp(this,260)));}}
}
