package com.alfahdtv.app;

import android.Manifest;import android.app.Activity;import android.app.AlertDialog;import android.app.DownloadManager;import android.app.PictureInPictureParams;import android.content.Intent;import android.content.SharedPreferences;import android.content.pm.PackageManager;import android.graphics.Color;import android.media.AudioManager;import android.net.Uri;import android.net.http.SslError;import android.os.Build;import android.os.Bundle;import android.os.Environment;import android.util.Rational;import android.view.GestureDetector;import android.view.Gravity;import android.view.MotionEvent;import android.view.View;import android.view.ViewGroup;import android.view.WindowManager;import android.webkit.CookieManager;import android.webkit.JavascriptInterface;import android.webkit.DownloadListener;import android.webkit.SslErrorHandler;import android.webkit.URLUtil;import android.webkit.WebChromeClient;import android.webkit.WebResourceError;import android.webkit.WebResourceRequest;import android.webkit.WebResourceResponse;import android.webkit.WebSettings;import android.webkit.WebView;import android.webkit.WebViewClient;import android.widget.Button;import android.widget.FrameLayout;import android.widget.LinearLayout;import android.widget.PopupWindow;import android.widget.ProgressBar;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;import java.util.HashSet;import java.util.Locale;import java.util.Set;

public final class MainActivity extends Activity {
    private WebView webView;private ProgressBar progress;private LinearLayout errorPanel,topBar;private FrameLayout root,splash;private View customView;private WebChromeClient.CustomViewCallback customCallback;private long lastBack;private SharedPreferences prefs,data;private String pendingDownload;private boolean touchLocked,websiteBackEnabled;
    @Override protected void onCreate(Bundle state){super.onCreate(state);prefs=getSharedPreferences("settings",0);data=getSharedPreferences("data",0);styleWindow();buildUi();decorateSplash();configureWebView();NotificationScheduler.schedule(this);requestNotificationPermission();if(state==null)webView.loadUrl(data.getString("last_url",BuildConfig.HOME_URL));else webView.restoreState(state);root.postDelayed(()->UpdateChecker.check(this,false),1800);}
    private void decorateSplash(){LinearLayout loading=new LinearLayout(this);loading.setOrientation(LinearLayout.VERTICAL);loading.setGravity(Gravity.CENTER_HORIZONTAL|Gravity.BOTTOM);loading.setPadding(0,0,0,AppUi.dp(this,54));TextView label=AppUi.text(this,"جاري التحميل…",15,AppUi.MUTED);label.setGravity(Gravity.CENTER);loading.addView(label,new LinearLayout.LayoutParams(-1,AppUi.dp(this,28)));LinearLayout dots=new LinearLayout(this);dots.setGravity(Gravity.CENTER);for(int i=0;i<3;i++){TextView dot=AppUi.text(this,"●",18,AppUi.RED);dot.setGravity(Gravity.CENTER);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(AppUi.dp(this,18),AppUi.dp(this,28));dots.addView(dot,p);final int delay=i*180;dot.animate().alpha(.25f).setDuration(500).setStartDelay(delay).withEndAction(()->dot.animate().alpha(1f).setDuration(500).setStartDelay(delay).start()).start();}loading.addView(dots,new LinearLayout.LayoutParams(-1,AppUi.dp(this,30)));splash.addView(loading,new FrameLayout.LayoutParams(-1,-1));}
    private void styleWindow(){getWindow().setStatusBarColor(AppUi.BG);getWindow().setNavigationBarColor(AppUi.BG);if(!BuildConfig.DEBUG&&prefs!=null&&prefs.getBoolean("secure",true))getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);}
    private void buildUi(){
        root=new FrameLayout(this);root.setBackgroundColor(AppUi.BG);LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);root.addView(shell,new FrameLayout.LayoutParams(-1,-1));
        topBar=new LinearLayout(this);topBar.setGravity(Gravity.CENTER_VERTICAL);topBar.setPadding(AppUi.dp(this,12),AppUi.dp(this,7),AppUi.dp(this,12),AppUi.dp(this,7));topBar.setBackgroundColor(Color.rgb(12,13,18));
        TextView logo=AppUi.text(this,"",20,Color.WHITE);logo.setGravity(Gravity.CENTER);logo.setBackgroundResource(R.drawable.fahd_logo);topBar.addView(logo,new LinearLayout.LayoutParams(AppUi.dp(this,40),AppUi.dp(this,40)));
        TextView title=AppUi.text(this,"  الفهد TV",20,Color.WHITE);title.setTypeface(null,1);topBar.addView(title,new LinearLayout.LayoutParams(0,-1,1));
        topBar.addView(barButton("☰",v->showSideMenu()));topBar.addView(barButton("⌂",v->webView.loadUrl(BuildConfig.HOME_URL)));topBar.addView(barButton("★",v->favoriteMenu()));topBar.addView(barButton("↓",v->startActivity(new Intent(this,DownloadsActivity.class))));shell.addView(topBar,new LinearLayout.LayoutParams(-1,AppUi.dp(this,56)));
        FrameLayout browser=new FrameLayout(this);webView=new WebView(this);browser.addView(webView,new FrameLayout.LayoutParams(-1,-1));progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);browser.addView(progress,new FrameLayout.LayoutParams(-1,AppUi.dp(this,3),Gravity.TOP));errorPanel=errorView();browser.addView(errorPanel,new FrameLayout.LayoutParams(-1,-1));shell.addView(browser,new LinearLayout.LayoutParams(-1,0,1));
        splash=new FrameLayout(this);splash.setBackgroundResource(R.drawable.fahd_splash);LinearLayout center=new LinearLayout(this);center.setOrientation(LinearLayout.VERTICAL);center.setGravity(Gravity.CENTER);TextView mark=AppUi.text(this,"",48,Color.WHITE);mark.setGravity(Gravity.CENTER);mark.setBackgroundResource(R.drawable.fahd_splash);center.addView(mark,new LinearLayout.LayoutParams(-1,-1));TextView name=AppUi.text(this,"الفهد TV",31,Color.WHITE);name.setGravity(Gravity.CENTER);name.setTypeface(null,1);name.setPadding(0,AppUi.dp(this,22),0,0);center.addView(name);TextView tag=AppUi.text(this,"مشاهدة أسرع • تجربة أذكى",14,AppUi.MUTED);tag.setGravity(Gravity.CENTER);tag.setPadding(0,AppUi.dp(this,8),0,0);center.addView(tag);splash.addView(center,new FrameLayout.LayoutParams(-1,-1));root.addView(splash,new FrameLayout.LayoutParams(-1,-1));setContentView(root);mark.setVisibility(View.GONE);mark.animate().alpha(1).scaleX(1).scaleY(1).setDuration(450).start();
    }
    private TextView barButton(String text,View.OnClickListener click){TextView b=AppUi.action(this,text);b.setOnClickListener(click);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(AppUi.dp(this,40),AppUi.dp(this,40));p.setMarginStart(AppUi.dp(this,7));b.setLayoutParams(p);return b;}
    private void showSideMenu(){
        final PopupWindow menu=new PopupWindow(this);FrameLayout shade=new FrameLayout(this);shade.setBackgroundColor(0xB8000000);LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(AppUi.dp(this,20),AppUi.dp(this,28),AppUi.dp(this,20),AppUi.dp(this,18));panel.setBackground(AppUi.round(AppUi.PANEL,28,this));FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(AppUi.dp(this,320),-1,Gravity.RIGHT);shade.addView(panel,pp);TextView title=AppUi.text(this,"\u0627\u0644\u0641\u0647\u062f TV",26,Color.WHITE);title.setTypeface(null,1);title.setGravity(Gravity.CENTER);panel.addView(title,new LinearLayout.LayoutParams(-1,AppUi.dp(this,62)));TextView sub=AppUi.text(this,"\u0645\u0643\u062a\u0628\u062a\u0643 \u0627\u0644\u0645\u0641\u0636\u0644\u0629",13,AppUi.MUTED);sub.setGravity(Gravity.CENTER);panel.addView(sub,new LinearLayout.LayoutParams(-1,AppUi.dp(this,36)));String[] labels={"\u2302  \u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629","\u25b6  \u0627\u0644\u0645\u0633\u0644\u0633\u0644\u0627\u062a","\u25a0  \u0627\u0644\u0623\u0641\u0644\u0627\u0645","\u2606  \u0627\u0644\u0623\u0646\u0645\u064a","\u25c9  \u0627\u0644\u0642\u0646\u0648\u0627\u062a","\u26bd  \u0645\u0628\u0627\u0631\u064a\u0627\u062a \u0627\u0644\u064a\u0648\u0645","\u2315  \u0627\u0644\u0628\u062d\u062b","\u2661  \u0627\u0644\u0645\u0641\u0636\u0644\u0629","\u2193  \u0627\u0644\u062a\u0646\u0632\u064a\u0644\u0627\u062a","\u2699  \u0627\u0644\u0625\u0639\u062f\u0627\u062f\u0627\u062a"};for(int i=0;i<labels.length;i++){final int item=i;TextView row=AppUi.text(this,labels[i],18,Color.WHITE);row.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);row.setPadding(AppUi.dp(this,12),0,AppUi.dp(this,12),0);panel.addView(row,new LinearLayout.LayoutParams(-1,AppUi.dp(this,47)));row.setOnClickListener(v->{menu.dismiss();if(item==0)webView.loadUrl(BuildConfig.HOME_URL);else if(item==1)webView.evaluateJavascript("openSeries()",null);else if(item==2)webView.evaluateJavascript("openArabic()",null);else if(item==5)webView.evaluateJavascript("openFootball()",null);else if(item==6)webView.evaluateJavascript("openSearch()",null);else if(item==7)startActivity(new Intent(this,LibraryActivity.class));else if(item==8)startActivity(new Intent(this,DownloadsActivity.class));else if(item==9)startActivity(new Intent(this,SettingsActivity.class));else toast("\u0642\u0633\u0645 \u0628\u0627\u0644\u062a\u0637\u0648\u064a\u0631");});}shade.setOnClickListener(v->menu.dismiss());panel.setOnClickListener(v->{});menu.setContentView(shade);menu.setWidth(-1);menu.setHeight(-1);menu.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(Color.TRANSPARENT));menu.setOutsideTouchable(true);menu.setFocusable(true);menu.setElevation(AppUi.dp(this,24));menu.showAtLocation(root,Gravity.RIGHT|Gravity.TOP,0,0);panel.setTranslationX(AppUi.dp(this,340));panel.animate().translationX(0).setDuration(240).start();
    }
    private LinearLayout errorView(){LinearLayout e=new LinearLayout(this);e.setOrientation(LinearLayout.VERTICAL);e.setGravity(Gravity.CENTER);e.setPadding(AppUi.dp(this,30),AppUi.dp(this,30),AppUi.dp(this,30),AppUi.dp(this,30));e.setBackgroundColor(AppUi.BG);TextView icon=AppUi.text(this,"⌁",58,AppUi.RED);icon.setGravity(Gravity.CENTER);e.addView(icon);TextView t=AppUi.text(this,"الاتصال مش مساعدنا",24,Color.WHITE);t.setGravity(Gravity.CENTER);t.setTypeface(null,1);e.addView(t);TextView m=AppUi.text(this,"تأكد من الإنترنت أو حاول بعد لحظات",15,AppUi.MUTED);m.setGravity(Gravity.CENTER);m.setPadding(0,AppUi.dp(this,10),0,AppUi.dp(this,22));e.addView(m);Button r=new Button(this);r.setText("إعادة المحاولة");r.setTextColor(Color.WHITE);r.setBackground(AppUi.round(AppUi.RED,13,this));r.setOnClickListener(v->{hideError();webView.reload();});e.addView(r,new LinearLayout.LayoutParams(AppUi.dp(this,200),AppUi.dp(this,52)));e.setVisibility(View.GONE);return e;}
    private void configureWebView(){WebView.setWebContentsDebuggingEnabled(BuildConfig.DEBUG);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(false);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setAllowFileAccessFromFileURLs(false);s.setAllowUniversalAccessFromFileURLs(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setMediaPlaybackRequiresUserGesture(!prefs.getBoolean("autoplay",true));s.setSupportMultipleWindows(false);s.setJavaScriptCanOpenWindowsAutomatically(false);s.setSaveFormData(false);s.setCacheMode(WebSettings.LOAD_NO_CACHE);s.setUserAgentString(s.getUserAgentString()+" AlFahdTV/2.0 Android");if(Build.VERSION.SDK_INT>=26)s.setSafeBrowsingEnabled(true);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(webView,false);webView.addJavascriptInterface(new NativePlayerBridge(),"AndroidPlayer");webView.addJavascriptInterface(new NativeNavigationBridge(),"NativeNavigation");webView.setWebViewClient(new SecureClient());webView.setWebChromeClient(new SecureChrome());webView.setDownloadListener(downloadListener);webView.setBackgroundColor(AppUi.BG);}
    private final DownloadListener downloadListener=(url,userAgent,disposition,mime,size)->{Uri uri=safeUri(url);if(uri==null||!isDownloadHost(uri.getHost())){toast("تم منع رابط تحميل غير موثوق");return;}pendingDownload=url;new AlertDialog.Builder(this).setTitle("تحميل الفيديو").setMessage("سيتم تنزيل الجودة المتاحة من المصدر داخل مجلد Downloads.").setNegativeButton("إلغاء",null).setPositiveButton("بدء التحميل",(d,w)->enqueue(url,userAgent,disposition,mime)).show();};
    private void enqueue(String url,String userAgent,String disposition,String mime){if(Build.VERSION.SDK_INT<=28&&checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},77);return;}try{String name=URLUtil.guessFileName(url,disposition,mime);DownloadManager.Request r=new DownloadManager.Request(Uri.parse(url));r.setTitle(name);r.setDescription("تحميل من الفهد TV");r.setMimeType(mime);r.addRequestHeader("User-Agent",userAgent);String cookie=CookieManager.getInstance().getCookie(url);if(cookie!=null)r.addRequestHeader("Cookie",cookie);r.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);r.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS,name);((DownloadManager)getSystemService(DOWNLOAD_SERVICE)).enqueue(r);toast("بدأ التحميل • تابعه من صفحة التنزيلات");}catch(Exception e){toast("تعذر بدء التحميل");}}
    private final class SecureClient extends WebViewClient {
        @Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return handle(r.getUrl());}@Override public boolean shouldOverrideUrlLoading(WebView v,String u){Uri x=safeUri(u);return x==null||handle(x);}
        private boolean handle(Uri u){String scheme=u.getScheme(),host=u.getHost();if(!"https".equalsIgnoreCase(scheme)){toast("تم منع رابط غير آمن");return true;}if(BuildConfig.ALLOWED_HOST.equalsIgnoreCase(host))return false;if(isDownloadHost(host)&&u.getPath()!=null&&u.getPath().contains("download")){downloadListener.onDownloadStart(u.toString(),webView.getSettings().getUserAgentString(),"","video/mp4",-1);return true;}toast("تم منع الانتقال إلى نطاق غير موثوق");return true;}
        @Override public void onPageStarted(WebView v,String u,android.graphics.Bitmap f){progress.setVisibility(View.VISIBLE);hideError();}
        @Override public void onPageFinished(WebView v,String u){progress.setVisibility(View.GONE);hideError();data.edit().putString("last_url",u).apply();saveHistory(u,v.getTitle());restorePlayback();if(splash.getVisibility()==View.VISIBLE)splash.animate().alpha(0).setDuration(280).withEndAction(()->splash.setVisibility(View.GONE)).start();}
        @Override public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame())showError();}@Override public void onReceivedHttpError(WebView v,WebResourceRequest r,WebResourceResponse e){if(r.isForMainFrame()&&e.getStatusCode()>=500)showError();}@Override public void onReceivedSslError(WebView v,SslErrorHandler h,SslError e){h.cancel();Uri failed=safeUri(e==null?null:e.getUrl());if(failed!=null&&BuildConfig.ALLOWED_HOST.equalsIgnoreCase(failed.getHost()))showError();}
    }
    private final class SecureChrome extends WebChromeClient {
        @Override public void onProgressChanged(WebView v,int n){progress.setProgress(n);progress.setVisibility(n<100?View.VISIBLE:View.GONE);}
        @Override public void onShowCustomView(View v,CustomViewCallback c){if(customView!=null){c.onCustomViewHidden();return;}customView=v;customCallback=c;installPlayerGestures(v);root.addView(v,new FrameLayout.LayoutParams(-1,-1));webView.setVisibility(View.GONE);topBar.setVisibility(View.GONE);setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);getWindow().getDecorView().setSystemUiVisibility(5894);}
        @Override public void onHideCustomView(){hideCustom();}
    }
    private void toggleFavorite(){String title=webView.getTitle(),url=webView.getUrl();if(url==null)return;Set<String> set=new HashSet<>(data.getStringSet("favorites",new HashSet<>()));String entry=(title==null?"محتوى":title)+"|"+url;boolean removed=false;for(String x:new HashSet<>(set))if(x.endsWith("|"+url)){set.remove(x);removed=true;}if(!removed)set.add(entry);data.edit().putStringSet("favorites",set).apply();toast(removed?"تمت الإزالة من المفضلة":"تمت الإضافة للمفضلة");}
    private void favoriteMenu(){new AlertDialog.Builder(this).setTitle("مكتبتي").setItems(new String[]{"إضافة أو إزالة الصفحة الحالية","فتح المفضلة وسجل المشاهدة"},(d,which)->{if(which==0)toggleFavorite();else startActivity(new Intent(this,LibraryActivity.class));}).show();}
    private void saveHistory(String url,String title){Set<String> set=new HashSet<>(data.getStringSet("history",new HashSet<>()));for(String x:new HashSet<>(set))if(x.endsWith("|"+url))set.remove(x);set.add((title==null?"الفهد TV":title)+"|"+url);while(set.size()>30)set.remove(set.iterator().next());data.edit().putStringSet("history",set).apply();}
    private void savePlayback(){if(webView==null)return;webView.evaluateJavascript("(function(){var v=document.querySelector('video');return v?JSON.stringify({t:v.currentTime||0,d:v.duration||0}):''})()",value->{if(value!=null&&!value.equals("\"\"")&&!value.equals("null"))data.edit().putString("playback_"+Integer.toHexString(String.valueOf(webView.getUrl()).hashCode()),value).apply();});}
    private void restorePlayback(){String key="playback_"+Integer.toHexString(String.valueOf(webView.getUrl()).hashCode()),raw=data.getString(key,"");if(raw.isEmpty())return;java.util.regex.Matcher m=java.util.regex.Pattern.compile("\\\\\"t\\\\\":([0-9.]+)").matcher(raw);if(m.find()){String t=m.group(1);webView.postDelayed(()->webView.evaluateJavascript("(function(){var v=document.querySelector('video');if(v&&"+t+">10&&"+t+"<v.duration-10)v.currentTime="+t+"})()",null),1200);}}
    private void hideCustom(){if(customView==null)return;root.removeView(customView);customView=null;webView.setVisibility(View.VISIBLE);topBar.setVisibility(View.VISIBLE);setRequestedOrientation(android.content.pm.ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);if(customCallback!=null)customCallback.onCustomViewHidden();customCallback=null;}
    private void enterPip(){if(Build.VERSION.SDK_INT>=26&&customView!=null&&prefs.getBoolean("pip",true)){try{enterPictureInPictureMode(new PictureInPictureParams.Builder().setAspectRatio(new Rational(16,9)).build());}catch(Exception ignored){}}}
    private void installPlayerGestures(View target){GestureDetector detector=new GestureDetector(this,new GestureDetector.SimpleOnGestureListener(){@Override public boolean onDown(MotionEvent e){return true;}@Override public boolean onDoubleTap(MotionEvent e){if(touchLocked){toast("اضغط مطولًا لفك قفل اللمس");return true;}int seconds=e.getX()<target.getWidth()/2?-10:10;webView.evaluateJavascript("(function(){var v=document.querySelector('video');if(v)v.currentTime=Math.max(0,Math.min(v.duration||999999,v.currentTime+"+seconds+"))})()",null);toast(seconds>0?"تقديم 10 ثوانٍ":"تأخير 10 ثوانٍ");return true;}@Override public void onLongPress(MotionEvent e){touchLocked=!touchLocked;toast(touchLocked?"تم قفل اللمس • اضغط مطولًا لفكه":"تم فك قفل اللمس");}@Override public boolean onScroll(MotionEvent first,MotionEvent now,float dx,float dy){if(touchLocked)return true;if(Math.abs(dy)<Math.abs(dx)||target.getHeight()==0)return false;float ratio=-dy/target.getHeight();if(first.getX()>target.getWidth()/2){AudioManager a=(AudioManager)getSystemService(AUDIO_SERVICE);int max=a.getStreamMaxVolume(AudioManager.STREAM_MUSIC),cur=a.getStreamVolume(AudioManager.STREAM_MUSIC);a.setStreamVolume(AudioManager.STREAM_MUSIC,Math.max(0,Math.min(max,cur+(int)(ratio*max*2))),0);}else{WindowManager.LayoutParams p=getWindow().getAttributes();float current=p.screenBrightness<0?.5f:p.screenBrightness;p.screenBrightness=Math.max(.05f,Math.min(1f,current+ratio));getWindow().setAttributes(p);}return true;}});target.setOnTouchListener((v,e)->{detector.onTouchEvent(e);return touchLocked;});}
    private Uri safeUri(String v){try{return Uri.parse(v);}catch(Exception e){return null;}}private boolean isDownloadHost(String h){if(h==null)return false;h=h.toLowerCase(Locale.ROOT);return h.equals("akwam.it")||h.endsWith(".akwam.it")||h.equals("downet.net")||h.endsWith(".downet.net");}
    private void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},88);}
    private final class NativePlayerBridge{@JavascriptInterface public void download(String url){runOnUiThread(()->downloadListener.onDownloadStart(url,webView.getSettings().getUserAgentString(),"","video/mp4",-1));}@JavascriptInterface public void play(String url){runOnUiThread(()->{if(url==null||!url.startsWith("https://")){toast("تم منع رابط غير آمن");return;}Intent i=new Intent(MainActivity.this,PlayerActivity.class);i.putExtra("media_url",url);startActivity(i);});}}
    private final class NativeNavigationBridge{@JavascriptInterface public void setBackEnabled(boolean enabled){websiteBackEnabled=enabled;}}
    private void showError(){errorPanel.setVisibility(View.VISIBLE);webView.setVisibility(View.GONE);progress.setVisibility(View.GONE);if(splash!=null)splash.setVisibility(View.GONE);}private void hideError(){errorPanel.setVisibility(View.GONE);webView.setVisibility(View.VISIBLE);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);String url=intent.getStringExtra("open_url");if(url!=null&&url.startsWith("https://"+BuildConfig.ALLOWED_HOST))webView.loadUrl(url);}@Override protected void onPause(){savePlayback();super.onPause();}@Override protected void onUserLeaveHint(){enterPip();super.onUserLeaveHint();}@Override protected void onSaveInstanceState(Bundle out){webView.saveState(out);super.onSaveInstanceState(out);}@Override public void onBackPressed(){if(customView!=null){hideCustom();return;}if(websiteBackEnabled){websiteBackEnabled=false;webView.evaluateJavascript("window.history.back()",null);return;}if(webView.canGoBack()){webView.goBack();return;}long now=System.currentTimeMillis();if(now-lastBack<1800)super.onBackPressed();else{lastBack=now;toast("اضغط رجوع مرة أخرى للخروج");}}@Override protected void onDestroy(){if(webView!=null){webView.stopLoading();webView.setWebChromeClient(null);webView.setWebViewClient(null);webView.destroy();}super.onDestroy();}
}
