package com.alfahdtv.app;

import android.app.Activity;import android.app.AlertDialog;import android.content.Intent;import android.content.SharedPreferences;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.webkit.CookieManager;import android.webkit.WebStorage;import android.webkit.WebView;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.Switch;import android.widget.TextView;import java.io.BufferedReader;import java.io.InputStreamReader;import java.net.HttpURLConnection;import java.net.URL;import java.nio.charset.StandardCharsets;import java.util.stream.Collectors;

public final class SettingsActivity extends Activity {
    private SharedPreferences prefs;
    @Override protected void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("settings",0);getWindow().setStatusBarColor(AppUi.BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(AppUi.dp(this,16),AppUi.dp(this,14),AppUi.dp(this,16),0);root.setBackgroundColor(AppUi.BG);TextView head=AppUi.text(this,"‹   إعدادات الفهد TV",23,Color.WHITE);head.setTypeface(null,1);head.setOnClickListener(v->finish());root.addView(head,new LinearLayout.LayoutParams(-1,AppUi.dp(this,58)));ScrollView scroll=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.addView(toggle("تنبيهات المحتوى الجديد","notifications",true));body.addView(toggle("صورة داخل صورة","pip",true));body.addView(toggle("تشغيل الفيديو تلقائيًا","autoplay",true));body.addView(toggle("حماية الشاشة من التصوير","secure",true));TextView update=AppUi.action(this,"فحص تحديثات التطبيق");update.setTextSize(15);update.setOnClickListener(v->checkUpdate(update));LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(-1,AppUi.dp(this,52));up.topMargin=AppUi.dp(this,8);body.addView(update,up);TextView clear=AppUi.action(this,"مسح الملفات المؤقتة");clear.setTextSize(15);clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("مسح الملفات المؤقتة؟").setMessage("لن يتم حذف التنزيلات.").setNegativeButton("إلغاء",null).setPositiveButton("مسح",(d,w)->{WebView web=new WebView(this);web.clearCache(true);web.destroy();WebStorage.getInstance().deleteAllData();CookieManager.getInstance().removeAllCookies(null);}).show());LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,AppUi.dp(this,52));cp.topMargin=AppUi.dp(this,10);body.addView(clear,cp);TextView version=AppUi.text(this,"الفهد TV • الإصدار "+BuildConfig.VERSION_NAME+"\nتطبيق مستقل ومحمي",13,AppUi.MUTED);version.setGravity(android.view.Gravity.CENTER);version.setPadding(0,AppUi.dp(this,30),0,AppUi.dp(this,30));body.addView(version);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private void checkUpdate(TextView button){button.setText("جاري الفحص...");button.setEnabled(false);new Thread(()->{String tag="";try{HttpURLConnection h=(HttpURLConnection)new URL("https://api.github.com/repos/amrsallam1/al-fahd-tv/releases").openConnection();h.setConnectTimeout(9000);h.setReadTimeout(9000);h.setRequestProperty("Accept","application/vnd.github+json");String body;try(BufferedReader r=new BufferedReader(new InputStreamReader(h.getInputStream(),StandardCharsets.UTF_8))){body=r.lines().collect(Collectors.joining());}java.util.regex.Matcher m=java.util.regex.Pattern.compile("\\\"tag_name\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"").matcher(body);if(m.find())tag=m.group(1);}catch(Exception ignored){}String result=tag;runOnUiThread(()->{button.setText("فحص تحديثات التطبيق");button.setEnabled(true);if(result.isEmpty())new AlertDialog.Builder(this).setMessage("تعذر فحص التحديثات الآن").setPositiveButton("حسنًا",null).show();else if(result.contains(BuildConfig.VERSION_NAME))new AlertDialog.Builder(this).setMessage("أنت تستخدم أحدث إصدار").setPositiveButton("حسنًا",null).show();else new AlertDialog.Builder(this).setTitle("يوجد تحديث جديد").setMessage("الإصدار المتاح: "+result).setNegativeButton("لاحقًا",null).setPositiveButton("تحميل",(d,w)->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://github.com/amrsallam1/al-fahd-tv/releases/latest")))).show();});}).start();}
    private Switch toggle(String title,String key,boolean def){Switch s=new Switch(this);s.setText(title);s.setTextSize(16);s.setTextColor(Color.WHITE);s.setChecked(prefs.getBoolean(key,def));s.setPadding(AppUi.dp(this,14),AppUi.dp(this,10),AppUi.dp(this,14),AppUi.dp(this,10));s.setBackground(AppUi.round(AppUi.PANEL,14,this));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,AppUi.dp(this,64));p.bottomMargin=AppUi.dp(this,10);s.setLayoutParams(p);s.setOnCheckedChangeListener((button,value)->{prefs.edit().putBoolean(key,value).apply();if(key.equals("notifications")){if(value)NotificationScheduler.schedule(this);else NotificationScheduler.cancel(this);}});return s;}
}
