org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=34
android.aapt2FromMavenOverride=C:/Users/IT SHOP/Documents/Codex/2026-08-03/new-chat/work/al-fahd-tv/.tools/aapt2/aapt2.exe
