pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri("$rootDir/local-maven") }
        google()
        mavenCentral()
    }
}
rootProject.name = 'AlFahdTV'
include ':app'
