package com.alfahdtv.app;

import android.app.Activity;import android.app.AlertDialog;import android.content.Intent;import android.content.SharedPreferences;import android.net.Uri;import android.os.Handler;import android.os.Looper;
import java.io.BufferedReader;import java.io.InputStreamReader;import java.net.HttpURLConnection;import java.net.URL;import java.nio.charset.StandardCharsets;import java.util.regex.Matcher;import java.util.regex.Pattern;

final class UpdateChecker {
    private static final String RELEASE_URL="https://api.github.com/repos/merom2854-sketch/elfahd/releases/latest";
    private UpdateChecker(){}
    static void check(Activity activity,boolean manual){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(RELEASE_URL).openConnection();c.setConnectTimeout(9000);c.setReadTimeout(9000);c.setRequestProperty("Accept","application/vnd.github+json");String json;try(BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8))){json=r.lines().collect(java.util.stream.Collectors.joining());}String tag=find(json,"tag_name"),apk=findApk(json);if(tag.isEmpty()||!newer(tag,BuildConfig.VERSION_NAME))return;SharedPreferences p=activity.getSharedPreferences("updates",0);if(!manual&&tag.equals(p.getString("seen", "")))return;p.edit().putString("seen",tag).apply();new Handler(Looper.getMainLooper()).post(()->new AlertDialog.Builder(activity).setTitle("تحديث جديد للفهد TV").setMessage("الإصدار "+tag+" متاح الآن.").setNegativeButton("لاحقًا",null).setPositiveButton("تحميل التحديث",(d,w)->{if(!apk.isEmpty())activity.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(apk)));else activity.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://github.com/merom2854-sketch/elfahd/releases/latest")));}).show());}catch(Exception e){if(manual)new Handler(Looper.getMainLooper()).post(()->new AlertDialog.Builder(activity).setMessage("تعذر فحص التحديثات الآن.").setPositiveButton("حسنًا",null).show());}}).start();}
    private static String find(String json,String key){Matcher m=Pattern.compile("\\\""+key+"\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"").matcher(json);return m.find()?m.group(1):"";}
    private static String findApk(String json){Matcher m=Pattern.compile("\\\"browser_download_url\\\"\\s*:\\s*\\\"([^\\\"]+\\.apk[^\\\"]*)\\\"").matcher(json);return m.find()?m.group(1).replace("\\/","/"):"";}
    private static boolean newer(String candidate,String current){String[] a=candidate.replaceAll("[^0-9.]","").split("\\."),b=current.replaceAll("[^0-9.]","").split("\\.");for(int i=0;i<Math.max(a.length,b.length);i++){int x=i<a.length?Integer.parseInt(a[i]):0,y=i<b.length?Integer.parseInt(b[i]):0;if(x!=y)return x>y;}return false;}
}
